In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Advanced_pandas_sales_dataset.csv")
df.head()

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30

###Q1. Dataset Exploration


Perform dataset exploration by displaying the first 10 rows, dataset structure, shape, and data types.

In [2]:
df.head(10)
df.info()
df.shape
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

###Explanation

This step is essential to understand the dataset before analysis. The head() function helps in viewing sample data, while info() provides details about columns, non-null values, and data types. The shape shows the number of rows and columns, and dtypes identifies whether the data is numerical or categorical. This understanding helps in selecting appropriate data processing and analysis techniques.

###Q2. Sales Filtering Analysis

Filter the dataset to display:

Orders where Sales > 3500
Orders where Region = "East" and Sales > 2500

In [3]:
df[df["Sales"] > 3500]

df[(df["Region"] == "East") & (df["Sales"] > 2500)]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
34,1035,2024-02-20,Nitin,Ahmedabad,East,Laptop,Electronics,2535,4,0.10,188.15
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
43,1044,2024-09-20,Kavya,Hyderabad,East,Printer,Office,2618,7,0.05,454.64
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
55,1056,2024-01-03,Sneha,Chennai,East,Headphones,Accessories,2784,4,0.05,474.60
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
76,1077,2024-03-02,Neha,Pune,East,Monitor,Electronics,2964,8,0.20,109.33
81,1082,2024-08-16,Isha,Chennai,East,Phone,Electronics,2720,4,0.15,163.13
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
108,1109,2024-10-23,Raj,Hyderabad,East,Tablet,Electronics,2509,4,0.05,371.67
109,1110,2024-11-28,Priya,Ahmedabad,East,Printer,Office,2561,4,0.20,57.96
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
179,1180,2024-12-13,Neha,Ahmedabad,East,Monitor,Electronics,2690,7,0.10,452.70
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
202,1203,2024-05-10,Rahul,Mumbai,East,Phone,Electronics,2901,8,0.15,252.25
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

###Explanation

Filtering helps in identifying high-value transactions. By selecting records where sales exceed a certain threshold, we can focus on important revenue-generating transactions. Combining multiple conditions (Region and Sales) provides deeper insights, such as identifying high-performing regions. This is useful for decision-making and targeted strategies.

###Q3. Customer Purchase Analysis


Identify the top 5 customers based on total sales.

In [7]:
df.groupby("Customer")["Sales"].sum().sort_values(ascending=False).head(5)

Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

###Explanation

Grouping data by customer and summing sales allows us to evaluate customer contribution. Sorting in descending order helps identify top customers who generate the highest revenue. These customers are valuable for the business and can be targeted for retention strategies, loyalty programs, and personalized marketing.

###Q4. Regional Sales Performance


Calculate the total sales generated by each region and identify the region with the highest revenue.

In [8]:
region_sales = df.groupby("Region")["Sales"].sum()

region_sales

region_sales.idxmax()

'East'

###Explanation

This analysis helps in understanding geographical performance. By aggregating sales region-wise, we can identify which regions contribute most to revenue. The idxmax() function helps in finding the top-performing region. Businesses can use this insight to allocate resources and expand operations in high-performing areas

###Q5. Product Performance Analysis


Calculate the total quantity sold for each product and identify the most popular product.

In [9]:
product_qty = df.groupby("Product")["Quantity"].sum()

product_qty

product_qty.idxmax()

'Monitor'

###Explanation

This step focuses on product demand. By summing quantity sold per product, we can identify which products are most popular among customers. This helps businesses in inventory planning, marketing focus, and production decisions.

###Q6. Multi-Level Grouping


Group the dataset by Region and Category and calculate total sales for each combination.

In [10]:
df.groupby(["Region", "Category"])["Sales"].sum()

Region  Category
East    Accessories     57646
        Electronics    160907
        Office          14122
North   Accessories     62052
        Electronics     70023
        Office          26135
South   Accessories     80914
        Electronics     86690
        Office          15504
West    Accessories     64811
        Electronics     84128
        Office          21288
Name: Sales, dtype: int64

###Explanation

Multi-level grouping provides a deeper level of analysis by combining multiple variables. It helps in understanding how different product categories perform across regions. This insight can guide targeted marketing strategies and region-specific product offerings.

###Q7. Pivot Table Creation


Create a pivot table showing:

Rows → Region
Columns → Product
Values → Total Sales

In [11]:
pivot = pd.pivot_table(df, values="Sales", index="Region", columns="Product", aggfunc="sum")

pivot

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

###Explanation

Pivot tables transform data into a structured format, making it easier to compare values across categories. This helps in identifying trends, such as which products perform well in specific regions. It simplifies complex data analysis.

###Q8. Profitability Analysis


Calculate the average profit for each product category and identify the most profitable category.

In [12]:
profit_cat = df.groupby("Category")["Profit"].mean()

profit_cat

profit_cat.idxmax()

'Office'

###Explanation

Profitability analysis helps in understanding which categories generate the most profit on average. This is important for pricing strategies, cost control, and business focus. High-profit categories can be prioritized for growth.

###Q9. Discount Impact Study


Analyze the relationship between discount and profit by calculating average profit for each discount level.

In [13]:
df.groupby("Discount")["Profit"].mean()

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

###Explanation

This analysis helps in understanding how discounts affect profitability. If higher discounts lead to lower profit, it indicates that excessive discounting may harm business margins. This insight is useful for designing pricing strategies.

###Q10. End-to-End Data Wrangling Task


Perform the following:

Filter dataset where Sales > 3000
Group by Region and Product
Calculate total sales
Convert into pivot table

In [14]:
filtered = df[df["Sales"] > 3000]

grouped = filtered.groupby(["Region", "Product"])["Sales"].sum()

pivot_final = grouped.unstack()

pivot_final

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          14469      9642   44096    16420  19000  29500     3696   29229
North          5326     15653    4540     5087  22209  24670    17185    3392
South         10026     19249   17950    14921  26928  18218    14143   19613
West          13898     33380    5922    14354   3511  15653    12648   17185

###Explanation

This is a complete data analysis workflow combining filtering, grouping, and reshaping. It focuses on high-value transactions and presents them in a structured format. This helps in identifying top-performing products in each region and supports strategic decision-making.